artifactory:
  artifactory:
    admin:
      password: "VMware1!"
  postgresql:
    postgresqlPassword: "NiT4XinSYI"
  service:
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - artifactory.hubau.cloud
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "contour"
      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
      - secretName: artifactory-tls
        hosts:
          - artifactory.hubau.cloud
  nginx:
    enabled: false
