---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: dhubau@vmware.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging
    # Add a single challenge solver using DNS
    solvers:
      - dns01:
          cloudDNS:
            project: pa-dhubau
            serviceAccountSecretRef:
              name: gcp-key
              key: gcp.key.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: dhubau@vmware.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt
    # Add a single challenge solver using DNS
    solvers:
      - dns01:
          cloudDNS:
            project: pa-dhubau
            serviceAccountSecretRef:
              name: gcp-key
              key: gcp.key.json