apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: zen
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: zen-demo
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: zen
    carto.run/workload-namespace: default
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/Turbots/gitops.git
      ref:
        branch: main
    subPath: config/team-tanzu/zen
