apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: zen-deliverable
spec:
  fetch:
  - git:
      url: https://github.com/Turbots/gitops
      ref: origin/main
      subPath: config/default/zen
  syncPeriod: 1m0s
  serviceAccountName: default
  deploy:
  - kapp:
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
  template:
  - ytt: {}
  - kbld: {}