apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: zen
  labels:
    app.kubernetes.io/part-of: zen-demo
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/pipeline: test
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
      autoscaling.knative.dev/maxScale: "10"
  source:
    git:
      url: https://github.com/Turbots/zen.git
      ref:
        branch: main
