apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: zen
  labels:
    app.kubernetes.io/part-of: zen-demo
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: 'true'
    apps.tanzu.vmware.com/pipeline: test
spec:
  source:
    git:
      url: https://github.com/Turbots/zen.git
      ref:
        branch: main
  params:
  - name: annotations
    value:
      # Target 10 requests in-flight per pod.
      autoscaling.knative.dev/target: "10"
      # Disable scale to zero with a min scale of 2 for High Availability.
      autoscaling.knative.dev/min-scale: "2"
      # Limit scaling to 10 pods.
      autoscaling.knative.dev/max-scale: "10"
  env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP