apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: zen
spec:
  destination:
    server: 'https://apps.calimesa.cf-app.com:8443'
    namespace: default
  source:
    repoURL: 'https://gitlab.hubau.cloud/root/gitops.git'
    targetRevision: master
    path: 'develop/zen'
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
