apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: zen
spec:
  destination:
    server: 'https://dhubau-aks-production-dns-2ca168fa.hcp.westeurope.azmk8s.io:443'
    namespace: dev
  source:
    repoURL: 'https://gitlab.tanzu.be/root/gitops.git'
    targetRevision: main
    path: 'develop/zen'
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
